name: "Usar la acción actirepo"
on:
  push:
    branches:
      - main

jobs:
  actirepo-job:
    runs-on: ubuntu-latest
    steps:
      # Usar la acción personalizada desde actirepo
      - name: Ejecutar actirepo
        uses: teuton-software/actirepo@main
        with:
          branch: "main"
          token: ${{ secrets.GITHUB_TOKEN }}
