name: "Usar la acción actirepo"
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  actirepo-job:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Usar la acción personalizada desde actirepo
      - name: Ejecutar actirepo
        uses: teuton-software/actirepo@main
        with:
          branch: "main"
          token: ${{ secrets.GITHUB_TOKEN }}
