name: "Usar la acción actirepo"
on:
  push:
    branches:
      - main
jobs:
  actirepo-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Ejecutar actirepo
        uses: teuton-software/actirepo@main
        with:
          branch: "main"
          token: ${{ secrets.GITHUB_TOKEN }}